- name: Mount root partition
  ansible.posix.mount:
    path: /mnt
    src: /dev/sda2
    fstype: btrfs
    opts: compress=zstd,subvol=root
    state: ephemeral
- name: Create home directory
  ansible.builtin.file:
    path: /mnt/home
    state: directory
    mode: '0755'
- name: Create nix directory
  ansible.builtin.file:
    path: /mnt/nix
    state: directory
    mode: '0755'
- name: Mount home partition
  ansible.posix.mount:
    path: /mnt/home
    src: /dev/sda2
    fstype: btrfs
    opts: compress=zstd,subvol=home
    state: ephemeral
- name: Mount nix partition
  ansible.posix.mount:
    path: /mnt/nix
    src: /dev/sda2
    fstype: btrfs
    opts: compress=zstd,subvol=nix,noatime
    state: ephemeral
- name: Create boot directory
  ansible.builtin.file:
    path: /mnt/boot
    state: directory
    mode: '0755'
- name: Mount boot partition
  ansible.posix.mount:
    path: /mnt/boot
    src: /dev/sda1
    fstype: vfat
    state: ephemeral
